<%-- 
    Document   : sentmail
    Created on : Jun 6, 2017, 6:51:31 PM
    Author     : Royalty
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@page import="com.resumeShowCase.*"%>
<%@page import="java.util.Date"%>

<!DOCTYPE html>
<html>
    <head>
        <title>SentMail::Resume</title>
        <meta charset="utf-8" />
        <meta name="keywords" content="Resume show case, peter eugene mbanda, resume example"/>
        <meta name="description" content="class projects Javascript, HTML, CSS, Java, Jsoup"/>
        <link rel="stylesheet" type="text/css" href="css\stylesch4.css" />
    </head>
    
    <body id="body">
        
    <header>
        <div style="text-align: center" id="body">
            <a style="background-color: #f9f5f3" href="resume.jsp"><img src="images\resumeimages.jpg" height="150" width="200" alt="resume logo" style="box-shadow: 10px 10px 15px #888888" /></a>
        </div>
    </header>
        <%
            User user = (User)request.getAttribute("user");
        %>
        <p>
            
        <h3>Message Sent Confirmation!</h3>
        
        Hello <span style="color: blue"><%=user.getName()%></span> your message has been sent successfully to our file for review. 
        The email on file is <span style="color: blue"><%=user.getEmail()%></span> with the following message
        
        </p>
        
        <p style="color: blue">
            <%=user.getMessage()%>
        </p>
        
       
        Please make sure that the email on file is correct otherwise please re-submit by linking 
        to the contact page or click the image and return to the home page.
        
        <p></p>
        This Website has been generated by :: <%=getServletInfo()%><br>
        My email based on the servlet context <span style="color:red">(*NOT REAL*)</span> :: <%=getServletContext().getInitParameter("email").toString()%>
        -> acquired by the ServletContext
        <p></p>
        <form action="contact.jsp">
            <input type="submit" value="Return">
        </form>
        
        
    <footer id="body" style="text-align: center">
        <small>Copyright &#169; 2017 Mansory Inc. All rights reserved -> No animals were harmed during creation of Website</small>
    </footer>
    </body>
</html>
